#############
# alacritty #
#############

# font
font:
  size: 12
  offset:
    x: 0
    y: 0
  # brew install font-fira-code-nerd-font
  normal:
    family: FiraCode Nerd Font Mono
    style: Retina
  italic:
    family: FiraCode Nerd Font Mono
    style: Light
  bold:
    family: FiraCode Nerd Font Mono
    style: Medium


key_bindings:
  - { key: J, mods: Command, chars: "\e[B" }
  - { key: K, mods: Command, chars: "\e[A" }
  - { key: J, mods: Command|Shift, action: ScrollHalfPageDown }
  - { key: K, mods: Command|Shift, action: ScrollHalfPageUp }
  - { key: Return, mods: Command, action: ToggleSimpleFullScreen }
  - { key: Q, mods: Command, chars: "" }

# Colors (Nord)
colors:
  primary:
    background: '0x2E3440'
    foreground: '0xD8DEE9'
  normal:
    black:   '0x3B4252'
    red:     '0xBF616A'
    green:   '0xA3BE8C'
    yellow:  '0xEBCB8B'
    blue:    '0x81A1C1'
    magenta: '0xB48EAD'
    cyan:    '0x88C0D0'
    white:   '0xE5E9F0'
  bright:
    black:   '0x4C566A'
    red:     '0xBF616A'
    green:   '0xA3BE8C'
    yellow:  '0xEBCB8B'
    blue:    '0x81A1C1'
    magenta: '0xB48EAD'
    cyan:    '0x8FBCBB'
    white:   '0xECEFF4'

# gruvbox_dark: https://github.com/eendroroy/alacritty-theme/blob/master/schemes.yaml
# colors:
#   primary:
#     # hard contrast: background = '0x1d2021'
#     background: '0x282828'
#       # soft contrast: background = '0x32302f'
#     foreground: '0xebdbb2'
#   normal:
#     black:   '0x282828'
#     red:     '0xcc241d'
#     green:   '0x98971a'
#     yellow:  '0xd79921'
#     blue:    '0x458588'
#     magenta: '0xb16286'
#     cyan:    '0x689d6a'
#     white:   '0xa89984'
#   bright:
#     black:   '0x928374'
#     red:     '0xfb4934'
#     green:   '0xb8bb26'
#     yellow:  '0xfabd2f'
#     blue:    '0x83a598'
#     magenta: '0xd3869b'
#     cyan:    '0x8ec07c'
#     white:   '0xebdbb2'


# # colorscheme (Dracula)
# colors:
#   # Default colors
#   primary:
#     background: '#282a36'
#     foreground: '#f8f8f2'
#   # Normal colors
#   normal:
#     black:   '#000000'
#     red:     '#ff5555'
#     green:   '#50fa7b'
#     yellow:  '#f1fa8c'
#     blue:    '#caa9fa'
#     magenta: '#ff79c6'
#     cyan:    '#8be9fd'
#     white:   '#bfbfbf'
#   # Bright colors
#   bright:
#     black:   '#575b70'
#     red:     '#ff6e67'
#     green:   '#5af78e'
#     yellow:  '#f4f99d'
#     blue:    '#caa9fa'
#     magenta: '#ff92d0'
#     cyan:    '#9aedfe'
#     white:   '#e6e6e6'
