#!/bin/sh

create_dotfile_link()
{
    ln -svf "$DOTDIR/$1" "$HOME/$2"
}

create_dotfile_link_same()
{
    create_dotfile_link "$1" "$1"
}

###############################################################################
# link dotfiles
###############################################################################

# dotfiles directory
[ -z "$DOTDIR" ] && DOTDIR=$(pwd) && export DOTDIR

# Creating links
create_dotfile_link_same .zshrc
create_dotfile_link_same .bashrc
create_dotfile_link_same .vimrc
create_dotfile_link_same .pluggins.vim
mkdir -p "$HOME/.vim/plugin"
create_dotfile_link grep.vim .vim/plugin/grep.vim

mkdir -p "$HOME/.xmonad"
create_dotfile_link xmonad.hs .xmonad/xmonad.hs

create_dotfile_link_same .gdbinit
create_dotfile_link_same .ghci
create_dotfile_link_same .gitconfig
create_dotfile_link_same .muttrc
create_dotfile_link_same .mailcap
create_dotfile_link_same .xinitrc
create_dotfile_link_same .zprofile

mkdir -p "$HOME/.config"
create_dotfile_link redshift.conf .config/redshift.conf

mkdir -p "$HOME/.config/dunst"
create_dotfile_link dunst/dunstrc .config/dunst/dunstrc

mkdir -p "$HOME/.newsboat"
create_dotfile_link_same .newsboat/config

# create_dotfile_link_same slock/config.def.h

ln -sv "$DOTDIR/bin" "$HOME/bin"

###############################################################################
# dependencies
###############################################################################

[ "$#" -ne 1 ] || [ ! "$1" = "-a" ] && exit 0
echo "Installing Dependencies"

###############################################################################
# vim Plug
PLUGFILE="$HOME/.vim/autoload/plug.vim"
PLUGURL='https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
[ ! -f "$PLUGFILE" ] && echo "Downloading plug.vim" && \
    curl -fLo "$PLUGFILE" --create-dirs "$PLUGURL"
echo "Installing plug.vim Pluggins"
vim -c "PlugInstall" -c "qa"

###############################################################################
# zsh pluggins

update_plugin()
{
    url="$1"
    dest_path="$2"
    if [ ! -d "$dest_path" ]
    then
        echo "Installing $dest_path"
        git clone "$url" "$dest_path"
    else
        echo "Updating $dest_path"
        git -C "$dest_path" pull
    fi
}

mkdir -p "$HOME/.zsh"
update_plugin 'https://github.com/sindresorhus/pure' "$HOME/.zsh/pure"
update_plugin 'https://github.com/zsh-users/zsh-syntax-highlighting' "$HOME/.zsh/zsh-syntax-highlighting"
update_plugin 'https://github.com/MichaelAquilina/zsh-you-should-use' "$HOME/.zsh/zsh-you-should-use"
