#!/bin/sh

# keynav daemonize               # moving the cursor around without the mouse
# clout push-watch &             # could with rsync

set -xv

[ ! "$(cat /etc/hostname)" = 'charles-thinkpad' ] &&
    redshift &                                  # filter blue light
dunst &                                         # notification daemon
unclutter --timeout 10 --fork                   # hide mouse after 10s
udiskie &                                       # automount usb devices
xrdb "$XDG_CONFIG_HOME/x11/Xresources"
hsetroot -add '#111' -add '#222' -gradient 180  # gradient background
syncthing --no-browser > ~/.cache/syncthing.log 2>&1 &

case "$(cat /etc/hostname)" in
    charles-main)
        if xrandr | grep -q 'DisplayPort-0 connected'
        then
            xrandr --output DisplayPort-0 --mode 3840x1080 --rate 68
        elif xrandr | grep 'HDMI-0 connected'
        then
            xrandr --output DVI-0  --auto                     --left-of DVI-1  \
                   --output DVI-1  --mode 1920x1080 --primary --left-of HDMI-0 \
                   --output HDMI-0 --mode 1920x1080
        else
            xrandr --output DVI-0  --auto                     --left-of DVI-1  \
                   --output DVI-1  --mode 1920x1080 --primary
        fi
        ;;
    charles-laptop)
        xrandr | grep -q 'VGA1.*connected' &&
        xrandr --output LVDS1 --primary --left-of VGA1 \
               --output VGA1 --mode 1280x1024
        ;;
    charles-fractal)
        if xrandr | grep -q 'HTMI-1 connected'
        then
            xrandr --output DP-2 --mode 3840x1080 --primary --left-of HDMI-1 \
                   --output HDMI-1 --mode 1920x1080
        fi
        # fix screen tearing
        nvidia-settings --assign CurrentMetaMode="nvidia-auto-select +0+0 { ForceFullCompositionPipeline = On }"
        ;;
    charles-thinkpad)
        # xmobar-toggle-hotcorner-check &
        ;;
    charles-north)
        xrandr --output DP-0 --mode 2560x1440 --pos 548x0 --rotate normal \
               --output DP-1 --off --output DP-2 --off --output DP-3 --off --output DP-4 --off --output DP-5 --off \
               --output HDMI-A-1-0 --mode 1920x1080 --pos 5120x1800 --rotate normal \
               --output DisplayPort-1-0 --primary --mode 5120x1440 --pos 0x1440 --rotate normal
        ;;
esac

# awesome
# gnome-session
xmonad || { xmonad --recompile; xmonad; }
