# from: https://yazi-rs.github.io/docs/tips
[[mgr.prepend_keymap]]
on = "<C-n>"
run = '''
    shell 'dragon-drop --and-exit --on-top "$@"' --confirm
'''
desc = "Open the drag and drop utility"

[[mgr.prepend_keymap]]
on = "!"
run = 'shell "$SHELL" --block --confirm'
desc = "Open shell in the current directory"

[[mgr.prepend_keymap]]
on = ["g", "d"]
run = 'cd ~/dl'
desc = "Open ~/dl"

[[mgr.prepend_keymap]]
on = "l"
run = 'plugin --sync smart-enter'
desc = "Enter the child directory, or open the file"
